name: Build Docker with Nix

on: [workflow_call, workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: polkadot-mayon

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and save Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: polkadot-mayon:${{ github.sha }}
        outputs: type=docker,dest=/tmp/mayon-docker.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v3
      with:
        name: mayon-docker
        path: /tmp/mayon-docker.tar
