name: Run workspace tests
on:
  - push

jobs:
  docker:
    uses: ./.github/workflows/mayon-docker.yaml

  checks:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Docker image
        uses: actions/download-artifact@v3
        with:
          name: mayon-docker
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/mayon-docker.tar
          docker image ls -a

      - name: Run tests
        run: |
          docker run -w /shellhere/polkadot \
                      -v $(pwd):/shellhere/polkadot \
                      --user "$(id -u):$(id -g)" \
                      polkadot-mayon:${{github.sha}} \
                      cargo test --workspace --release
